{
 "title": "Home Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "location",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: v.defaultBucket,\n  tag: \"location\"\n)"
   },
   {
    "name": "simulated",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: v.defaultBucket,\n  tag: \"simulated\"\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Door",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "base = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => contains(value: r.simulated, set: ${simulated:json}))\n  |> filter(fn: (r) => contains(value: r.location, set: ${location:json}))\n\nbase\n  |> filter(fn: (r) => r._measurement == \"door\")\n  |> filter(fn: (r) => r._field == \"open\")"
    }
   ]
  },
  {
   "title": "Motion",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "base = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => contains(value: r.simulated, set: ${simulated:json}))\n  |> filter(fn: (r) => contains(value: r.location, set: ${location:json}))\n\nbase\n  |> filter(fn: (r) => r._measurement == \"motion\")\n  |> filter(fn: (r) => r._field == \"detected\")"
    }
   ]
  },
  {
   "title": "Temperature (°C)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "base = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => contains(value: r.simulated, set: ${simulated:json}))\n  |> filter(fn: (r) => contains(value: r.location, set: ${location:json}))\n\nbase\n  |> filter(fn: (r) => r._measurement == \"temperature\")\n  |> filter(fn: (r) => r._field == \"temperature\")"
    }
   ]
  },
  {
   "title": "Humidity (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "base = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => contains(value: r.simulated, set: ${simulated:json}))\n  |> filter(fn: (r) => contains(value: r.location, set: ${location:json}))\n\nbase\n  |> filter(fn: (r) => r._measurement == \"temperature\")\n  |> filter(fn: (r) => r._field == \"humidity\")"
    }
   ]
  }
 ]
}